include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"
  
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors  
    missing_return: error
    # Treat invalid assignments as errors
    invalid_assignment: error

linter:
  rules:
    # Allow print in CLI tools and examples - appropriate for CLI package
    avoid_print: false
    # Allow dynamic calls for translation API responses  
    avoid_dynamic_calls: false
    # Allow async IO for file operations in CLI tools
    avoid_slow_async_io: false
    # Allow long lines for documentation and URLs
    lines_longer_than_80_chars: false
    # Allow cascade_invocations flexibility for CLI builders
    cascade_invocations: false
    # Allow mutable classes to have equals/hashCode in data models
    avoid_equals_and_hash_code_on_mutable_classes: false
    # Allow comment references for code documentation
    comment_references: false
    
    # Keep important quality rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_pub_dependencies: true
